# PyTorch

In [1]:
import torch

In [2]:
x = torch.rand(5)

In [3]:
print(x)

tensor([0.1724, 0.9421, 0.0061, 0.8799, 0.2736])


In [4]:
torch.cuda.is_available()

False

## Tensors 

In [9]:
torch.empty(2, 5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [10]:
torch.rand(2, 3)

tensor([[0.8103, 0.9477, 0.8371],
        [0.7099, 0.9244, 0.3933]])

In [14]:
torch.randint(low = 0, high = 100, size = (4, 5, ))

tensor([[40, 24, 52, 24, 68],
        [42, 90, 51, 81, 95],
        [31, 68,  5, 24, 95],
        [98, 39,  3, 89, 31]])

In [15]:
torch.zeros(5)

tensor([0., 0., 0., 0., 0.])

In [16]:
torch.ones(3)

tensor([1., 1., 1.])

In [21]:
x = torch.empty(5, dtype=torch.float16)

In [22]:
x

tensor([ 0.0000,  0.0000, 60.7500,  1.9824,  0.0000], dtype=torch.float16)

In [23]:
x.dtype

torch.float16

In [24]:
x.size()

torch.Size([5])

In [25]:
torch.tensor([1, 2, 3, 4.4])

tensor([1.0000, 2.0000, 3.0000, 4.4000])

In [26]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)

In [27]:
x, y

(tensor([[0.0591, 0.3029],
         [0.3484, 0.1218]]),
 tensor([[0.0129, 0.0371],
         [0.8678, 0.0473]]))

In [28]:
x + y

tensor([[0.0720, 0.3400],
        [1.2162, 0.1691]])

    In PyTorch, any function ending with an underscore "_" is an inplace operation.

In [29]:
y.add_(x)

tensor([[0.0720, 0.3400],
        [1.2162, 0.1691]])

In [30]:
y

tensor([[0.0720, 0.3400],
        [1.2162, 0.1691]])

## NumPY `array` and PyTorch `tensor`

In [31]:
import numpy as np

In [32]:
a = torch.rand(5)

In [33]:
type(a)

torch.Tensor

In [34]:
b = a.numpy()

In [35]:
type(b)

numpy.ndarray

In [37]:
print(a, "\n", b)

tensor([0.0319, 0.8696, 0.6602, 0.9933, 0.0645]) 
 [0.03186959 0.8695725  0.6601506  0.99327546 0.064484  ]


In [38]:
a.add_(1)

tensor([1.0319, 1.8696, 1.6602, 1.9933, 1.0645])

In [39]:
b

array([1.0318696, 1.8695725, 1.6601505, 1.9932754, 1.064484 ],
      dtype=float32)

    a and b share the same memory location if in CPU

In [40]:
a = np.ones(5)

In [41]:
a

array([1., 1., 1., 1., 1.])

In [42]:
b = torch.from_numpy(a)

In [43]:
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [44]:
b.add_(1)

tensor([2., 2., 2., 2., 2.], dtype=torch.float64)

In [45]:
a

array([2., 2., 2., 2., 2.])

## Autograd in PyTorch

In [109]:
np.random.seed(12345)
np.random.randn(13)

array([-0.20470766,  0.47894334, -0.51943872, -0.5557303 ,  1.96578057,
        1.39340583,  0.09290788,  0.28174615,  0.76902257,  1.24643474,
        1.00718936, -1.29622111,  0.27499163])

In [110]:
torch.manual_seed(12345)
x = torch.randn(3)
x

tensor([ 1.4271, -1.8701, -1.1962])

In [111]:
torch.manual_seed(1234)
x = torch.randn(3, requires_grad = True)
x

tensor([ 0.0461,  0.4024, -1.0115], requires_grad=True)

In [112]:
y = x+2
y

tensor([2.0461, 2.4024, 0.9885], grad_fn=<AddBackward0>)

In [113]:
z = y*y*2
z

tensor([ 8.3733, 11.5431,  1.9541], grad_fn=<MulBackward0>)

In [114]:
z.backward()

RuntimeError: grad can be implicitly created only for scalar outputs

        RuntimeError: grad can be implicitly created only for scalar outputs

In the background it's a vector jacobian product and if the value is not scalar when doing backward propogation, then we need to give another tensor into the `backward` function for it to propogate.

In [115]:
z = z.mean()
z

tensor(7.2902, grad_fn=<MeanBackward0>)

In [116]:
x.grad

In [117]:
z.backward()

In [118]:
x.grad

tensor([2.7282, 3.2032, 1.3180])

In [121]:
x.grad[0].item() # to get the full value

2.7281739711761475